# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loadingwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide6 import QtGui, QtWidgets
import PySide6
from . resources_rc import *

class Ui_LoadWindow(object):
    def setupUi(self, LoadWindow):
        LoadWindow.setObjectName("LoadWindow")
        LoadWindow.setEnabled(True)
        LoadWindow.resize(365, 100)
        LoadWindow.setMinimumSize(PySide6.QtCore.QSize(365, 100))
        LoadWindow.setMaximumSize(PySide6.QtCore.QSize(365, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("../../../../../../Desktop/Poisk-0.8.3/icon.ico"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        LoadWindow.setWindowIcon(icon)
        LoadWindow.setWindowOpacity(1.0)
        LoadWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(LoadWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color: rgb(15, 14, 25);\n"
"font: 12pt \"DM Sans\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"border: 0px solid black;\n"
"border-radius: 0px; \n"
"color: rgb(159, 157, 144); \n"
"background-color: rgb(1, 1, 5);\n"
"\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.info_text = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.info_text.setFont(font)
        self.info_text.setStyleSheet("color: rgb(180, 180, 180)")
        self.info_text.setAlignment(PySide6.QtCore.Qt.AlignCenter)
        self.info_text.setObjectName("info_text")
        self.verticalLayout.addWidget(self.info_text)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border: 1px solid black;\n"
"    border-radius: 0px;\n"
"    text-align: center\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(230, 5, 64);\n"
"    width: 1px;\n"
"    margin: 0px;\n"
"}")
        self.progressBar.setProperty("value", 22)
        self.progressBar.setAlignment(PySide6.QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(False)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addWidget(self.frame)
        LoadWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadWindow)
        PySide6.QtCore.QMetaObject.connectSlotsByName(LoadWindow)

    def retranslateUi(self, LoadWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadWindow.setWindowTitle(_translate("LoadWindow", "Tilda - Loading"))
        self.info_text.setText(_translate("LoadWindow", "Preparing Application"))
