# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'closetoapply.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtGui, QtWidgets
import PySide6
from . resources_rc import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 140)
        MainWindow.setMinimumSize(PySide6.QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(PySide6.QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background-color: rgb(15, 14, 25);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"font: 12pt \"DM Sans\";\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titlebar_frame = QtWidgets.QFrame(self.frame)
        self.titlebar_frame.setMinimumSize(PySide6.QtCore.QSize(0, 32))
        self.titlebar_frame.setMaximumSize(PySide6.QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.titlebar_frame.setFont(font)
        self.titlebar_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(0,0,0);\n"
"border: 1px solid black;\n"
"}")
        self.titlebar_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titlebar_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titlebar_frame.setObjectName("titlebar_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.titlebar_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.titlebar_frame)
        self.pushButton_3.setMaximumSize(PySide6.QtCore.QSize(25, 25))
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/primary_ui_elems/ui_elements/media/tilda_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(PySide6.QtCore.QSize(25, 25))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.title = QtWidgets.QLabel(self.titlebar_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setMinimumSize(PySide6.QtCore.QSize(0, 32))
        self.title.setMaximumSize(PySide6.QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel{\n"
"color: rgb(222, 222, 222);\n"
"font: 12pt \"DM Sans\";\n"
"}")
        self.title.setAlignment(PySide6.QtCore.Qt.AlignLeading|PySide6.QtCore.Qt.AlignLeft|PySide6.QtCore.Qt.AlignVCenter)
        self.title.setWordWrap(False)
        self.title.setIndent(0)
        self.title.setObjectName("title")
        self.horizontalLayout_5.addWidget(self.title)
        self.verticalLayout_3.addWidget(self.titlebar_frame)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogtext = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.dialogtext.setFont(font)
        self.dialogtext.setStyleSheet("QLabel{\n"
"color: rgb(180, 180, 180);;\n"
"font: 12pt \"DM Sans\";\n"
"}")
        self.dialogtext.setAlignment(PySide6.QtCore.Qt.AlignCenter)
        self.dialogtext.setWordWrap(True)
        self.dialogtext.setObjectName("dialogtext")
        self.verticalLayout_2.addWidget(self.dialogtext)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.dialogbox_buttonframe = QtWidgets.QFrame(self.frame)
        self.dialogbox_buttonframe.setMinimumSize(PySide6.QtCore.QSize(420, 45))
        self.dialogbox_buttonframe.setMaximumSize(PySide6.QtCore.QSize(420, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.dialogbox_buttonframe.setFont(font)
        self.dialogbox_buttonframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dialogbox_buttonframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dialogbox_buttonframe.setObjectName("dialogbox_buttonframe")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.dialogbox_buttonframe)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(290, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.dialogbox_buttonframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(PySide6.QtCore.QSize(40, 30))
        self.pushButton_2.setMaximumSize(PySide6.QtCore.QSize(40, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"border: 2px solid rgb(26,26,39);\n"
"border-radius: 5px; \n"
"color: rgb(180, 180, 180); \n"
"font: 10pt \"DM Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.dialogbox_buttonframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(PySide6.QtCore.QSize(60, 30))
        self.pushButton.setMaximumSize(PySide6.QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: 2px solid rgb(26,26,39);\n"
"border-radius: 5px; \n"
"color: rgb(180, 180, 180); \n"
"font: 10pt \"DM Sans\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_3.addWidget(self.dialogbox_buttonframe)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        PySide6.QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = PySide6.QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Tilda ~ Close to Apply"))
        self.dialogtext.setText(_translate("MainWindow", "Tilda will now exit to apply all changes. Be sure to manually restart the app afterwards!"))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))
        self.pushButton.setText(_translate("MainWindow", "Cancel"))

