# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_window_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from . resources_rc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 115)
        MainWindow.setMinimumSize(QtCore.QSize(420, 115))
        MainWindow.setMaximumSize(QtCore.QSize(420, 115))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(1, 1, 5);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dialogtext = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.dialogtext.setFont(font)
        self.dialogtext.setStyleSheet("color: rgb(180, 180, 180);")
        self.dialogtext.setAlignment(QtCore.Qt.AlignCenter)
        self.dialogtext.setWordWrap(True)
        self.dialogtext.setObjectName("dialogtext")
        self.verticalLayout_2.addWidget(self.dialogtext)
        self.verticalLayout.addWidget(self.frame)
        self.dialogbox_buttonframe = QtWidgets.QFrame(self.centralwidget)
        self.dialogbox_buttonframe.setMinimumSize(QtCore.QSize(420, 40))
        self.dialogbox_buttonframe.setMaximumSize(QtCore.QSize(420, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.dialogbox_buttonframe.setFont(font)
        self.dialogbox_buttonframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dialogbox_buttonframe.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dialogbox_buttonframe.setObjectName("dialogbox_buttonframe")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.dialogbox_buttonframe)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(275, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.dialogbox_buttonframe)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(60, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(60, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: 2px solid rgb(26,26,39);\n"
"border-radius: 5px; \n"
"color: rgb(180, 180, 180); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_20.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.dialogbox_buttonframe)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dialogtext.setText(_translate("MainWindow", "Tilda will now exit to apply changes. Be sure to manually restart the app afterwards!"))
        self.pushButton.setText(_translate("MainWindow", "Close"))
