# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
import PySide6
from . resources_rc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(333, 138)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"font: 12pt \"DM Sans\";\n"
"background-color: rgb(13,12,23);\n"
"color: rgb(180,180,180);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainframe = QtWidgets.QFrame(self.centralwidget)
        self.mainframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainframe.setObjectName("mainframe")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainframe)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titlebar_frame = QtWidgets.QFrame(self.mainframe)
        self.titlebar_frame.setMinimumSize(PySide6.QtCore.QSize(0, 32))
        self.titlebar_frame.setMaximumSize(PySide6.QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.titlebar_frame.setFont(font)
        self.titlebar_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(0,0,0);\n"
"border: 1px solid black;\n"
"}")
        self.titlebar_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titlebar_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.titlebar_frame.setObjectName("titlebar_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.titlebar_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.titlebar_frame)
        self.pushButton_3.setMaximumSize(PySide6.QtCore.QSize(25, 25))
        self.pushButton_3.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/primary_ui_elems/ui_elements/media/tilda_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(PySide6.QtCore.QSize(25, 25))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_5.addWidget(self.pushButton_3)
        self.title = QtWidgets.QLabel(self.titlebar_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.title.setFont(font)
        self.title.setStyleSheet("QLabel{\n"
"color: rgb(222, 222, 222);\n"
"font: 12pt \"DM Sans\";\n"
"}")
        self.title.setAlignment(PySide6.QtCore.Qt.AlignLeading|PySide6.QtCore.Qt.AlignLeft|PySide6.QtCore.Qt.AlignVCenter)
        self.title.setWordWrap(False)
        self.title.setIndent(0)
        self.title.setObjectName("title")
        self.horizontalLayout_5.addWidget(self.title)
        self.button_frame = QtWidgets.QFrame(self.titlebar_frame)
        self.button_frame.setMinimumSize(PySide6.QtCore.QSize(93, 30))
        self.button_frame.setMaximumSize(PySide6.QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.button_frame.setFont(font)
        self.button_frame.setLayoutDirection(PySide6.QtCore.Qt.LeftToRight)
        self.button_frame.setStyleSheet("")
        self.button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 2)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_5.addWidget(self.button_frame)
        self.verticalLayout_2.addWidget(self.titlebar_frame)
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainframe)
        self.stackedWidget.setObjectName("stackedWidget")
        self.updatedialog = QtWidgets.QWidget()
        self.updatedialog.setObjectName("updatedialog")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.updatedialog)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.body_frame = QtWidgets.QFrame(self.updatedialog)
        self.body_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.body_frame.setObjectName("body_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.body_frame)
        self.verticalLayout_3.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.body_frame)
        self.frame_3.setMinimumSize(PySide6.QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(PySide6.QtCore.QSize(16777215, 30))
        self.frame_3.setSizeIncrement(PySide6.QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.body_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(PySide6.QtCore.QSize(16777215, 30))
        self.label_2.setAlignment(PySide6.QtCore.Qt.AlignLeading|PySide6.QtCore.Qt.AlignLeft|PySide6.QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.updatebuttonframe = QtWidgets.QFrame(self.frame_4)
        self.updatebuttonframe.setMaximumSize(PySide6.QtCore.QSize(16777215, 40))
        self.updatebuttonframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.updatebuttonframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.updatebuttonframe.setObjectName("updatebuttonframe")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.updatebuttonframe)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.updatebuttonframe)
        self.pushButton.setMaximumSize(PySide6.QtCore.QSize(50, 40))
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: 2px solid rgb(26,26,39);\n"
"border-radius: 5px; \n"
"color: rgb(180, 180, 180); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.updatebuttonframe)
        self.pushButton_2.setEnabled(True)
        self.pushButton_2.setMaximumSize(PySide6.QtCore.QSize(50, 40))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"border: 2px solid rgb(26,26,39);\n"
"border-radius: 5px; \n"
"color: rgb(180, 180, 180); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.updatebuttonframe)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout_7.addWidget(self.body_frame)
        self.stackedWidget.addWidget(self.updatedialog)
        self.updateprogress = QtWidgets.QWidget()
        self.updateprogress.setObjectName("updateprogress")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.updateprogress)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.body_frame_2 = QtWidgets.QFrame(self.updateprogress)
        self.body_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body_frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.body_frame_2.setObjectName("body_frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.body_frame_2)
        self.verticalLayout_8.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_6 = QtWidgets.QFrame(self.body_frame_2)
        self.frame_6.setMinimumSize(PySide6.QtCore.QSize(0, 30))
        self.frame_6.setMaximumSize(PySide6.QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.frame_6.setFont(font)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.verticalLayout_8.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.body_frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMaximumSize(PySide6.QtCore.QSize(16777215, 16777215))
        self.label_4.setAlignment(PySide6.QtCore.Qt.AlignLeading|PySide6.QtCore.Qt.AlignLeft|PySide6.QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_11.addWidget(self.label_4)
        self.verticalLayout_10.addWidget(self.frame_8)
        self.updatebuttonframe_2 = QtWidgets.QFrame(self.frame_7)
        self.updatebuttonframe_2.setMaximumSize(PySide6.QtCore.QSize(16777215, 40))
        self.updatebuttonframe_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.updatebuttonframe_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.updatebuttonframe_2.setObjectName("updatebuttonframe_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.updatebuttonframe_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.updatebuttonframe_2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setMinimumSize(PySide6.QtCore.QSize(60, 0))
        self.pushButton_4.setMaximumSize(PySide6.QtCore.QSize(60, 40))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"border: 2px solid rgb(26,26,39);\n"
"border-radius: 5px; \n"
"color: rgb(180, 180, 180); \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    color: rgb(180, 180, 180); \n"
"    background-color: rgb(26,26,39);\n"
"    border-width: 0px;\n"
"    border-color: black;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_10.addWidget(self.updatebuttonframe_2)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.verticalLayout_12.addWidget(self.body_frame_2)
        self.stackedWidget.addWidget(self.updateprogress)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.mainframe)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        PySide6.QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = PySide6.QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Tilda ~ Update Manager"))
        self.label.setText(_translate("MainWindow", "New Tilda Version Found!"))
        self.label_2.setText(_translate("MainWindow", "Would you like to update to "))
        self.pushButton.setText(_translate("MainWindow", "Yes"))
        self.pushButton_2.setText(_translate("MainWindow", "No"))
        self.label_3.setText(_translate("MainWindow", "Updating! Please do not exit application."))
        self.label_4.setText(_translate("MainWindow", "Downloading ..."))
        self.pushButton_4.setText(_translate("MainWindow", "Apply"))

